# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-HtmlTree
version:      0.97
version_from: lib/Pod/HtmlTree.pm
installdirs:  site
requires:
    Cwd:                           0
    Exporter:                      0
    File::Basename:                0
    File::Find:                    0
    File::Path:                    0
    File::Spec:                    0
    Pod::Html:                     0
    Text::Wrap:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
